name: Test Study
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

on:
    workflow_dispatch:
    # pull_request:
    # push:
    schedule:
    # Run every 6 days to keep our caches alive
    - cron: '0 0 */6 * *'
jobs:
  deploy-raspberry-image:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      # - name: Install git
      #   run: sudo apt install -y git

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Test
        run: |
          $PWD 
          ls
        
